spring.application.name=caching-app



spring.datasource.url=jdbc:postgresql://localhost:5432/cs_caching_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configurations
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
#spring.data.redis.host=redis-19138.c212.ap-south-1-1.ec2.redns.redis-cloud.com
#spring.data.redis.port=19138
#spring.data.redis.password=VXsbF7ZB07xhTOpqjPN2kZP1n9vC45Ds
#spring.data.redis.ssl.enabled=false